name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main' # Run this action when you push to your default branch
      - 'feat/svelte-improvements' # Run this action when you push to the feat/svelte-improvements branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload production assets
        uses: actions/upload-pages-artifact@v5
        with:
          # If using SvelteKit, it outputs to 'build'. If using Vanilla Vite, change this to 'dist'.
          path: 'build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

